### ISSUE TITLE
Adding storage drops to emergency mode

### ISSUE THREAD

**Issue by malcolmlewis** [openSUSE/fuel-ignition#7]
Hi
The json generated/downloaded storage/file entry contains for example ;

```
"source": "data:text/plain;charset=utf-8;,PermitRootLogin%20yes%0APasswordAuthentication%20yes"
```

After generating the iso image (I'm using vagrant/libvirt) with; 

```
mkisofs -o $(pwd)/ignition.iso -V ignition disk
```

It drops to emergency mode again...

If I edit out the `text/plain;charset=utf-8;` and create the iso image again system boots to login prompt fine.

No issues bringing the instance up if I just generate a user/passwd (Hash Yourself) and no storage.

Operating System: opensuse/MicroOS.x86_64 (libvirt, 16.0.0.20220521)

**Comment by faeller** [comment]
Hi @malcolmlewis :) I've since changed the data source type in the Create Files section, if you paste the same string in data and data-vagrant, you get an identical file.

data encodes it in base64-unicode whereas data-vagrant is plaintext, is there some usecase where it's preferable to have it in plaintext, if not, is it okay if I remove data-vagrant? Thanks a lot!

**Comment by malcolmlewis** [comment]
> Hi @malcolmlewis :) I've since changed the data source type in the Create Files section, if you paste the same string in data and data-vagrant, you get an identical file.
> 
> data encodes it in base64-unicode whereas data-vagrant is plaintext, is there some usecase where it's preferable to have it in plaintext, if not, is it okay if I remove data-vagrant? Thanks a lot!

Hi @faeller just tested the change and all good with vagrant now so can be removed. Many thanks :+1:
